### ISSUE TITLE
Missing `SDL_GetWindowID` function

### ISSUE THREAD

**Issue by FoxieFlakey** [GabrielFrigo4/SDL-Sharp#39]
[SDL_GetWindowID](https://wiki.libsdl.org/SDL_GetWindowID)

**Comment by FoxieFlakey** [comment]
Im using it for filter events for a specific window 
```cs
if (ev.Window.WindowID == SDL.GetWindowID(specificWindow)) {
  // Do something for that specific window
}
```

**Comment by GabrielFrigo4** [comment]
I just added the Get Window ID function, in nuget version 1.3.0, check if it works

**Comment by FoxieFlakey** [comment]
ok let me check

**Comment by FoxieFlakey** [comment]
ok its working thanks for the help
