### ISSUE TITLE
Return of SDL.CreateWindow can't be checked for null

### ISSUE THREAD

**Issue by Shadowblitz16** [GabrielFrigo4/SDL-Sharp#40]
Return of SDL.CreateWindow can't be checked for null because it returns a struct which can't be null.
Try returning a `Window?`

**Comment by Shadowblitz16** [comment]
Looks like CreateRenderer and other method can't return null either

**Comment by GabrielFrigo4** [comment]
Well, in fact, it can't be verified as 'null', but I think it can be verified as 'IntPtr.Zero', I'll take a look and see some tests and return with a more solid answer

**Comment by Shadowblitz16** [comment]
@GabrielFrigo4 the problem is it returns a struct so if nullables as errors is on you can't

I would recommend returning a `struct?`

**Comment by GabrielFrigo4** [comment]
Well, as far as I know Allowing these structures to be nullable may not work, so I added a method to these structures that returns true if the IntPtr or void* is null or false if not (var.IsNull)

**Comment by Shadowblitz16** [comment]
ok ty.
