### ISSUE TITLE
Nuget please?

### ISSUE THREAD

**Issue by Shadowblitz16** [GabrielFrigo4/SDL-Sharp#42]
Please add this to nuget.org
It makes it easier to setup and use

**Comment by GabrielFrigo4** [comment]
There is already the nuget, the link to it is in the [README.md](https://github.com/GabrielFrigo4/SDL-Sharp/blob/master/README.md) of this repository, has the nuget of [SDL-Sharp](https://www.nuget.org/packages//SDL-Sharp/) and the DLLs of SDL for Windows that is called [SDL-Sharp-DLL](https://www.nuget.org/packages//SDL-Sharp-DLL/).
