### ISSUE TITLE
AudioSpec.Format type issue

### ISSUE THREAD

**Issue by gaboru** [GabrielFrigo4/SDL-Sharp#43]
AudioSpec.Format type is a short but should be ushort. It does not match the values of AudioFormatFlags. For example: AudioFormatFlags.F32 is not possible because of the short value range.

**Comment by GabrielFrigo4** [comment]
Hello, really the type looked wrong, I changed it here in the code. Could you test and confirm that it's working right before I release a new nuget?
To test it, you just need to download the nuget file in beta mode 2.2.3-beta2
[SDL_AudioFormat](https://wiki.libsdl.org/SDL2/SDL_AudioFormat)
[SDL_AudioSpec](https://wiki.libsdl.org/SDL2/SDL_AudioSpec)

**Comment by gaboru** [comment]
Hello,

I cannot test it sorry.

Regards,
Gabor

GabrielFrigo ***@***.***> ezt írta (időpont: 2023. nov. 26.,
V 17:06):

**Comment by GabrielFrigo4** [comment]
Ok, in that case I'll consider it as problem solved, since I actually had a problem with the types and I fixed them (apparently now everything is fine)
