### ISSUE TITLE
Missing Functionality

### ISSUE THREAD

**Issue by JohnRudy** [GabrielFrigo4/SDL-Sharp#44]
Missing functionality which should be present in SDL2. 

Most of these have been present since version 2.0.0
https://wiki.libsdl.org/SDL2/SDL_HasIntersection
https://wiki.libsdl.org/SDL2/SDL_HasIntersectionF
https://wiki.libsdl.org/SDL2/SDL_IntersectFRect
https://wiki.libsdl.org/SDL2/SDL_IntersectFRectAndLine
https://wiki.libsdl.org/SDL2/SDL_IntersectRect
https://wiki.libsdl.org/SDL2/SDL_IntersectRectAndLine

Looking at the SDL2 source code, they are present. 
Could it be possible to get these added to the bindings?

**Comment by GabrielFrigo4** [comment]
> Missing functionality which should be present in SDL2.
> 
> Most of these have been present since version 2.0.0 https://wiki.libsdl.org/SDL2/SDL_HasIntersection https://wiki.libsdl.org/SDL2/SDL_HasIntersectionF https://wiki.libsdl.org/SDL2/SDL_IntersectFRect https://wiki.libsdl.org/SDL2/SDL_IntersectFRectAndLine https://wiki.libsdl.org/SDL2/SDL_IntersectRect https://wiki.libsdl.org/SDL2/SDL_IntersectRectAndLine
> 
> Looking at the SDL2 source code, they are present. Could it be possible to get these added to the bindings?

I can add these functions.  But I think it's interesting that you add it, for this you must fork my repository and edit it in yours, then you must make a PR (pull request) and if everything meets the standards I will accept it and the changes will already be in my repository.

But if you really don't want to make a PR.  You can let me add this code.

**Comment by JohnRudy** [comment]
I currently don't have the time and know-how to do this myself, so I would not fork and make the PR. 

Taking a look at SDL2 source code there seems to be some new functionality and fixes also. 
I would assume a update to use 2.30.0 would be more beneficial than adding only some functionality back to the bindings. 

The original functionality I mentioned are a none issue to me, because they can be implemented by other means for now.

**Comment by GabrielFrigo4** [comment]
So in this case I'm going to add these functions, I'll probably do it in about 2 weeks, as I'm traveling.

**Comment by JohnRudy** [comment]
I have found some other functionality also missing... mainly from the audio side... I'll fork the repo but it might be faster for you to add these for now. I'll see if I get the time to start combing through the base and add what I find missing.

**Comment by GabrielFrigo4** [comment]
I know it has some functions, like some of Vulkan, and some "safe" structures that are also missing.  I intend to add this on my next vacation, making a major update (including making the repository more user-friendly and organized).  But I didn't know there was a lack of functions in the audio section... I'll also take a look at that

**Comment by JohnRudy** [comment]
I'll mark this issue as closed then. I haven't been able to get the time to add these myself. I'll look for the update once it's out then.
