### ISSUE TITLE
SDL_hints

### ISSUE THREAD

**Issue by TheEmperorE2** [GabrielFrigo4/SDL-Sharp#49]
Hi, SDL_hints is missing in this library, can you extend the library this feature?

I need to set SDL_RENDER_VSYNC and others.

#region SDL_hints.h
https://github.com/flibitijibibo/SDL2-CS/blob/master/src/SDL2.cs

**Comment by GabrielFrigo4** [comment]
Hi, I'll try to add this, if you want you can fork SDL-Sharp and add it, but if you don't want it I'll add :) myself

> Hi, SDL_hints is missing in this library, can you extend the library this feature?
> 
> I need to set SDL_RENDER_VSYNC and others.
> 
> #region SDL_hints.h https://github.com/flibitijibibo/SDL2-CS/blob/master/src/SDL2.cs

**Comment by GabrielFrigo4** [comment]
> Hi, SDL_hints is missing in this library, can you extend the library this feature?
> 
> I need to set SDL_RENDER_VSYNC and others.
> 
> #region SDL_hints.h https://github.com/flibitijibibo/SDL2-CS/blob/master/src/SDL2.cs

I added the SDL_hints
check if it works correctly
